CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    content text,
    is_user boolean NOT NULL,
    "timestamp" timestamp(6) without time zone,
    user_id character varying(255)
);

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.exercises (
    id bigint NOT NULL,
    category character varying(255),
    description text,
    duration integer,
    instructions text,
    mood_type character varying(255),
    title character varying(255) NOT NULL
);

ALTER TABLE public.exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.mood_entry (
    id bigint NOT NULL,
    anger_score double precision NOT NULL,
    joy_score double precision NOT NULL,
    overall_sentiment double precision NOT NULL,
    sadness_score double precision NOT NULL,
    "timestamp" timestamp(6) without time zone,
    user_message text,
    user_id character varying(255)
);

ALTER TABLE public.mood_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mood_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(20),
    preferences text,
    progress text,
    updates character varying(500),
    created_at timestamp(6) with time zone,
    date_of_birth date,
    email_notifications boolean,
    full_name character varying(100),
    is_active boolean,
    is_email_verified boolean,
    last_login_at timestamp(6) with time zone,
    login_count integer,
    profile_picture_url character varying(255),
    refresh_token character varying(512),
    sms_notifications boolean,
    updated_at timestamp(6) with time zone,
    verification_token character varying(255)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mood_entry
    ADD CONSTRAINT mood_entry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
