-- Create table to track completed exercises
CREATE TABLE public.user_exercises (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    exercise_id bigint NOT NULL,
    completed_at timestamp(6) with time zone DEFAULT now(),
    CONSTRAINT user_exercises_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user_exercises_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_user_exercises_exercise FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);

ALTER TABLE public.user_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Seed Short Duration Exercises (1-3 mins)
INSERT INTO exercises (title, category, duration, mood_type, description, instructions) VALUES
('30-Second Reset', 'Breathing', 1, 'Overwhelmed', 'A quick reset for when you fee panicked.', '1. Close your eyes.\n2. Take a deep breath in for 4 seconds.\n3. Sigh it out loudly.\n4. Open your eyes and name 3 things you see.'),

('Hand on Heart', 'Grounding', 2, 'Anxious', 'Physical touch to soothe the nervous system.', '1. Place your hand on your heart.\n2. Feel the warmth of your hand.\n3. Feel your chest rise and fall with each breath.\n4. Say to yourself "I am safe".'),

('Shoulder Drop', 'Relaxation', 1, 'Tense', 'Release tension in your shoulders instantly.', '1. Raise your shoulders up to your ears.\n2. Hold for 3 seconds.\n3. Drop them down completely.\n4. Repeat 3 times.'),

('Sip of Water', 'Mindfulness', 2, 'Restless', 'Mindful hydration.', '1. Take a sip of water.\n2. Hold it in your mouth for a moment.\n3. Notice the temperature and texture.\n4. Swallow slowly and feel it go down.');
